### ISSUE TITLE
Gmail Activation Link getting expried after 1sec and login uses

### ISSUE THREAD

**Issue by bhupenjp** [shahriarsajeeb/Eshop-tutorial#8]
Gmail Activation Link getting expried after 1sec i am sending you screen shot 
![Screenshot 2023-07-05 174733](https://github.com/shahriarsajeeb/Eshop-tutorial/assets/123988538/545f22d2-8e36-4d5a-bbcb-c3b4e9d8fdfa)
 
and second issue is login user
email fill
password fill
but stell error message i am attaching screen shots
![Screenshot 2023-07-04 145349](https://github.com/shahriarsajeeb/Eshop-tutorial/assets/123988538/bdfccba4-ff13-493b-9ab6-97d9d0f3630c)

**Comment by Nithishkumarr** [comment]
Data is storing in DB? In my code data is not storing

**Comment by bhupenjp** [comment]
> Data is storing in DB? In my code data is not storing

yes data is stor in DB.

**Comment by Jerald13** [comment]
I fixed. My issues was the model folder user.js did not implement 

```
const jwt = require("jsonwebtoken")  

// jwt token
userSchema.methods.getJwtToken = function () {
  return jwt.sign({ id: this._id }, process.env.JWT_SECRET_KEY, {
    expiresIn: process.env.JWT_EXPIRES,
  })
}
```

**Comment by Sumit-sky** [comment]
userSchema File ?

**Comment by Somto-ob** [comment]
> I fixed. My issues was the model folder user.js did not implement
> 
> ```
> const jwt = require("jsonwebtoken")  
> 
> // jwt token
> userSchema.methods.getJwtToken = function () {
>   return jwt.sign({ id: this._id }, process.env.JWT_SECRET_KEY, {
>     expiresIn: process.env.JWT_EXPIRES,
>   })
> }
> ``

How did you fix it? My code looks the same and still not working

**Comment by Somto-ob** [comment]
> Gmail Activation Link getting expried after 1sec i am sending you screen shot ![Screenshot 2023-07-05 174733](https://private-user-images.githubusercontent.com/123988538/251146929-545f22d2-8e36-4d5a-bbcb-c3b4e9d8fdfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NzA0MTIsIm5iZiI6MTcxNDQ3MDExMiwicGF0aCI6Ii8xMjM5ODg1MzgvMjUxMTQ2OTI5LTU0NWYyMmQyLThlMzYtNGQ1YS1iYmNiLWMzYjRlOWQ4ZmRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwOTQxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjMwZjI2NjlhZTE0YWY5OTcyZWFjOWRmNmMzY2ExNzVhNWJiMDVlZjFjZGY3MGUwM2IyNDI0NjU4MDY4Yjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Y8awOkByhpGbtu8lr2oYvOktRya6t-BauPVnHYuXF4)
> 
> and second issue is login user email fill password fill but stell error message i am attaching screen shots ![Screenshot 2023-07-04 145349](https://private-user-images.githubusercontent.com/123988538/251147411-bdfccba4-ff13-493b-9ab6-97d9d0f3630c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NzA0MTIsIm5iZiI6MTcxNDQ3MDExMiwicGF0aCI6Ii8xMjM5ODg1MzgvMjUxMTQ3NDExLWJkZmNjYmE0LWZmMTMtNDkzYi05YWI2LTk3ZDlkMGYzNjMwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwOTQxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjA2NTUwOGMzMGIxZDFlYmQ1MjBlNWJiN2U5OTc5MGEyOTMyMTRmYTAwYWEwYzc0MWIwMjFhZDczMzllMzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wFdNTJqMX2-Dr1d7Hlt4tR9WdAmP9BGaMVfdTXA8Tfw)

Did you find solution to this problem?
